### ISSUE TITLE
WSUS Cleanup scripts

### ISSUE THREAD

**Issue by ii-batman** [prae1809/PowerShell-Scripts#3]
@prae1809 
Long shot here... but I need a script to clean up wsus declined and superseded updates and you seem to have something on the old [gallery](https://social.msdn.microsoft.com/Forums/en-US/4d54c327-5041-4442-a08a-d45feebeb585/sccm-2012-delete-expired-and-superseeded-updates?forum=configmanagersecurity)
Would you be so kind to share it here? or if you have something better?
Thanks, M

**Comment by prae1809** [comment]
Hello,

This was not my script. See here :
Clean Software Update Groups console extension for ConfigMgr 2012 - MSEndpointMgr<https://msendpointmgr.com/2015/03/15/clean-software-update-groups-console-extension-for-configmgr-2012/>

Benoit Lecours | MVP
System Center Dudes
Website | www.systemcenterdudes.com<http://www.systemcenterdudes.com/>
Twitter | @SCDudes
***@***.***D77F05.7262F190]



From: ii-batman ***@***.***>
Sent: Thursday, July 22, 2021 10:34 AM
To: prae1809/PowerShell-Scripts ***@***.***>
Cc: Benoit Lecours ***@***.***>; Mention ***@***.***>
Subject: [prae1809/PowerShell-Scripts] WSUS Cleanup scripts (#3)


@prae1809<https://github.com/prae1809>
Long shot here... but I need a script to clean up wsus declined and superseded updates and you seem to have something on the old gallery<https://social.msdn.microsoft.com/Forums/en-US/4d54c327-5041-4442-a08a-d45feebeb585/sccm-2012-delete-expired-and-superseeded-updates?forum=configmanagersecurity>
Would you be so kind to share it here? or if you have something better?
Thanks, M

**Comment by ii-batman** [comment]
@prae1809 
Thanks - closing this issue.
