### ISSUE TITLE
Clean Script Run Not Creating Collections

### ISSUE THREAD

**Issue by jonconwayuk** [prae1809/PowerShell-Scripts#7]
After removing the 'Operational' collection and all of it's contents and running the script again on my Site Server I get errors straight after the script creates the new 'Operational' folder:

__GENUS               : 2
__CLASS               : SMS_ObjectContainerNode
__SUPERCLASS          : SMS_BaseClass
__DYNASTY             : SMS_BaseClass
__RELPATH             : SMS_ObjectContainerNode.ContainerNodeID=16789506
__PROPERTY_COUNT      : 11
__DERIVATION          : {SMS_BaseClass}
__SERVER              : CM01
__NAMESPACE           : root\sms\site_LAB
__PATH                : \\CM01\root\sms\site_LAB:SMS_ObjectContainerNode.ContainerNodeID=16789506
ContainerNodeID       : 16789506
FolderFlags           : 0
FolderGuid            : B0A44590-216E-4335-9712-FA2BAB0AD9F4
IsEmpty               : True
Name                  : Operational
ObjectType            : 5000
ObjectTypeName        : SMS_Collection_Device
ParentContainerNodeID : 0
SearchFolder          : False
SearchString          :
SourceSite            : LAB
PSComputerName        : CM01

-----------------
There was an error creating the: Office 365 Build Version | 1802 collection.
-----------------
Press Enter to continue...:
-----------------
There was an error moving the: Office 365 Build Version | 1802 collection to Operational.
-----------------
Press Enter to continue...:
-----------------
There was an error creating the: Office 365 Build Version | 1803 collection.
-----------------
Press Enter to continue...:
-----------------
There was an error moving the: Office 365 Build Version | 1803 collection to Operational.
-----------------
Press Enter to continue...:

etc.

This continues for every collection in the script and once processing completes there is just an empty 'Operational' folder in the console.

**Comment by kingofi88** [comment]
Add a space in line 73 after the = so 
$Schedule =New-CMSchedule –RecurInterval Days –RecurCount 7 
to 
$Schedule = New-CMSchedule –RecurInterval Days –RecurCount 7
Took me an hour to get it up and running.

**Comment by jonconwayuk** [comment]
You're a legend. Working now. Thank you very much :-)
